### ISSUE TITLE
Collect Earth dataset

### ISSUE THREAD

**Issue by sandersson-sylvera** [wri/sentinel-tree-cover#30]
Hello there! I was wondering, are there plans to make the Collect Earth Online dataset publicly available?

Best regards,
Simon

**Comment by JohnMBrandt** [comment]
Hi @sandersson-sylvera , we will release the CEO dataset and the model weights after the paper is through peer-review. Will keep you posted!

**Comment by JohnMBrandt** [comment]
Hey! We are wrapping up expanding the data to tropical scale and will be submitting our paper in the next month or two. You can see the (in progress) data here: https://jombrandt.users.earthengine.app/view/sentinel-tree-cover

When we submit the paper, we will work towards open sourcing more of the model / training data / standardizing the code and methodology to be more replicable. Any particular requests?

**Comment by Psancs05** [comment]
It would be great to have a list / file with all the versions of the different packages (python, tf, etc.) because installing the dependencies of _requirements.txt_ with Anaconda gives errors due to the different versions.

The rest of the work is very good 👍

**Comment by JohnMBrandt** [comment]
Hope this is helpful

boto3==1.9.167
python-dotenv>=0.5.1
scipy==1.2.1
sentinelhub==3.4.0
scikit-image==0.18.2
keras==2.2.4
tqdm==4.61.2
pandas==1.3.5
hickle==4.0.1
geopandas==0.9.0
pycountry==20.7.3
reverse_geocoder
pycountry_convert==0.7.2
numpy==1.21.5
rasterio==1.2.6
bottleneck==1.3.4
