### ISSUE TITLE
Model files release

### ISSUE THREAD

**Issue by ib-albo** [wri/sentinel-tree-cover#47]
Hi!
Any chance of releasing the model files, now that that the academic publication is published?

Love your work, thanks :)

**Comment by JohnMBrandt** [comment]
Hi -- the model files and a good chunk of the training data should be released in the next few weeks. I have waited till the updated Sentinel-2 collection 1 (https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/copernicus-sentinel-2-collection-1-availability-status) is released, and am fine-tuning the model on the new collection. 

The model will be released as a tensor flow 2 compatible frozen graph for inference and legacy tf 1.15 graph for resumable training. The data will be released as geotifs
